version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-podcast
    ports:
      - "3307:3306"    # змінено з 3306 на 3307
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: podcast_service

  postgres:
    image: postgres:16.2
    container_name: postgres-user
    ports:
      - "5433:5432"    # змінено з 5432 на 5433
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service

  podcast-service:
    build: ./podcast-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/podcast_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
      - USER_SERVICE_URL=http://user-service:8081
    depends_on:
      - mysql
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - podcast-service
      - user-service